twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar:
                - ['Undo', 'Redo']
                - ['Bold', 'Italic']
                - ['BulletedList', 'NumberedList']
                - ['Link', 'Image', 'Table', 'Video']
                - ['Calculator', 'Math', 'Emoji']
                - ['Maximize', 'Source']
            uiColor: '#ffffff'
            height: 200
            extraPlugins: 'calculator,math,emoji,video'
            removePlugins: 'elementspath'
            allowedContent: true
