# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/latest/
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    
    google:
        enabled: true
        issuer: naja7ni
        server_name: naja7ni.com
        template: security/2fa_form.html.twig
